GET http://localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MzUwMDE2NTUsImV4cCI6MTczNTAwMTY3NSwiYXVkIjoiNjc2YTA1MmZiZWIzNTI1ZTExZDNjOGViIiwiaXNzIjoiYWRhbS5jb20ifQ.enIQiHi1sHRi_VrVcUjv4rlcZQYBJiU-qOxxT1mCumg


###LOGIN
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "hhbyuvusniadhgham109@gmail.com",
    "password": "123456"
}
###router
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "hhbyuvusniadhgham109@gmail.com",
    "password": "123456"
}
###router
POST http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
    "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MzUwMDE1NzAsImV4cCI6MTc2NjU1OTE3MCwiYXVkIjoiNjc2YTA1MmZiZWIzNTI1ZTExZDNjOGViIiwiaXNzIjoiYWRhbS5jb20ifQ.r2vdmM3nnlJ2gXbDKe8mSxND_IvAGnB1DhgJZZLPMOg"
}